version: '3'
services:
  ansible:
    container_name: ansible_lab
    build: ./Docker/Ansible_Control_node
    tty: true
    working_dir: "/var/data"
    volumes:
      - ./ansible_lab_volume/:/var/data

  server01:
    container_name: server01
    build: ./Docker/Target_Server
    tty: true
  server02:
    container_name: server02
    build: ./Docker/Target_Server
    tty: true

volumes:
  ansible_playbooks:
